package com.frost289.naisiinvoices
import com.google.firebase.Timestamp
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import kotlinx.coroutines.tasks.await

class NaisiRepository(private val db:FirebaseFirestore){
 private fun line(m:Map<String,Any?>)=LineItem((m["qty"] as? Number)?.toDouble()?:0.0,m["desc"] as? String?:"",(m["price"] as? Number)?.toDouble()?:0.0,m["productName"] as? String,m["packLabel"] as? String,(m["packQuantity"] as? Number)?.toDouble(),m["productId"] as? String)
 suspend fun role(email:String):String?{val d=db.collection("config").document("roles").get().await().data?:return null;return when{(d["managers"]as?List<*>)?.contains(email)==true->"manager";(d["submitters"]as?List<*>)?.contains(email)==true->"submitter";(d["deliverers"]as?List<*>)?.contains(email)==true->"delivery";else->null}}
 suspend fun products()=db.collection("products").orderBy("productName").get().await().documents.map{d->Product(d.id,d.getString("productName")?:"",d.getString("packLabel")?:"",d.getDouble("quantity")?:0.0,d.getDouble("price")?:0.0,d.getDouble("stockOnHand")?:0.0)}
 suspend fun customers()=db.collection("customers").orderBy("name").get().await().documents.map{d->Customer(d.id,d.getString("name")?:"",d.getString("phone")?:"",d.getString("location")?:"",d.getDouble("lat"),d.getDouble("lng"),d.getBoolean("active")?:true,d.getString("assignedDay"))}
 suspend fun invoices()=db.collection("invoices").orderBy("createdAt",Query.Direction.DESCENDING).limit(25).get().await().documents.map{d->Invoice(d.id,d.getString("invoiceNo")?:"",d.getString("date")?:"",d.getString("customer")?:"",d.getString("customerId"),d.getString("phone")?:"",d.getString("location")?:"",d.getString("terms")?:"",d.getString("providerPhone")?:"",d.getString("notes")?:"",(d.get("items")as?List<Map<String,Any?>>)?.map(::line)?:emptyList(),d.getDouble("grandTotal")?:0.0)}
 suspend fun orders(role:String,uid:String)= (if(role=="submitter")db.collection("orders").whereEqualTo("createdBy",uid).orderBy("createdAt",Query.Direction.DESCENDING) else db.collection("orders").orderBy("createdAt",Query.Direction.DESCENDING)).limit(25).get().await().documents.map{d->Order(d.id,d.getString("orderNo")?:"",d.getString("status")?:"",d.getString("customerId"),d.getString("customerName")?:"",d.getString("customerPhone")?:"",d.getString("customerLocation")?:"",(d.get("items")as?List<Map<String,Any?>>)?.map(::line)?:emptyList(),d.getString("notes")?:"",d.getDouble("grandTotal")?:0.0,d.getString("createdBy")?:"",d.getString("createdByEmail")?:"")}
 suspend fun expenses(role:String,uid:String)= (if(role=="manager")db.collection("expenses") else db.collection("expenses").whereEqualTo("createdBy",uid)).orderBy("date",Query.Direction.DESCENDING).limit(25).get().await().documents.map{d->Expense(d.id,d.getString("date")?:"",d.getString("category")?:"",d.getDouble("amount")?:0.0,d.getString("notes")?:"",d.getString("createdBy")?:"",d.getString("createdByEmail")?:"")}
 suspend fun addCustomer(c:Customer,uid:String){db.collection("customers").add(mapOf("name" to normalizeText(c.name),"phone" to c.phone,"location" to normalizeText(c.location),"lat" to c.lat,"lng" to c.lng,"active" to true,"assignedDay" to c.assignedDay,"createdBy" to uid,"createdAt" to Timestamp.now(),"updatedAt" to Timestamp.now())).await()}
 suspend fun addProduct(p:Product,uid:String){db.collection("products").add(mapOf("productName" to p.productName,"packLabel" to p.packLabel,"quantity" to p.quantity,"price" to p.price,"stockOnHand" to p.stockOnHand,"createdBy" to uid,"createdAt" to Timestamp.now(),"updatedAt" to Timestamp.now())).await()}
 suspend fun addExpense(e:Expense,uid:String,email:String){db.collection("expenses").add(mapOf("date" to e.date,"category" to e.category,"amount" to e.amount,"notes" to e.notes,"createdBy" to uid,"createdByEmail" to email,"createdAt" to Timestamp.now(),"updatedAt" to Timestamp.now())).await()}
 private fun itemMap(i:LineItem)=mapOf("qty" to i.qty,"desc" to i.desc,"price" to i.price,"total" to i.total,"productName" to i.productName,"packLabel" to i.packLabel,"packQuantity" to i.packQuantity,"productId" to i.productId)
 suspend fun submitOrder(o:Order,uid:String,email:String):String{val ref=db.collection("orderCounters").document("naisiOrder");val no=db.runTransaction{tx->val s=tx.get(ref);val n=s.getLong("counter")?:1;tx.set(ref,mapOf("counter" to n+1));"ORD-${java.util.Calendar.getInstance().get(java.util.Calendar.YEAR)}-${n.toString().padStart(4,'0')}"}.await();db.collection("orders").add(mapOf("orderNo" to no,"status" to "Submitted","customerId" to o.customerId,"customerName" to o.customerName,"customerPhone" to o.customerPhone,"customerLocation" to o.customerLocation,"items" to o.items.map(::itemMap),"notes" to o.notes,"grandTotal" to o.items.sumOf{it.total},"createdBy" to uid,"createdByEmail" to email,"createdAt" to Timestamp.now(),"updatedAt" to Timestamp.now(),"submittedAt" to Timestamp.now(),"approvedAt" to null,"rejectedAt" to null,"cancelledAt" to null,"invoicedAt" to null,"managerNotes" to "","invoiceId" to null,"invoiceNo" to null)).await();return no}
 suspend fun addInvoice(i:Invoice,uid:String):String{val ref=db.collection("counters").document("naisiInvoice");val no=db.runTransaction{tx->val s=tx.get(ref);val p=s.getString("prefix")?:"NF-INV";val n=s.getLong("counter")?:1;tx.set(ref,mapOf("prefix" to p,"counter" to n+1));invoiceNo(p,n)}.await();db.collection("invoices").add(mapOf("invoiceNo" to no,"date" to i.date,"customer" to i.customer,"customerId" to i.customerId,"phone" to i.phone,"location" to i.location,"terms" to i.terms,"providerPhone" to i.providerPhone,"notes" to i.notes,"items" to i.items.map(::itemMap),"grandTotal" to i.items.sumOf{it.total},"createdBy" to uid,"createdAt" to Timestamp.now())).await();return no}
 suspend fun approveOrderWithStock(o:Order,uid:String,email:String){
  db.runTransaction { tx ->
   val orderRef=db.collection("orders").document(o.id);val os=tx.get(orderRef)
   if(!os.exists()||os.getString("status")!="Submitted") throw IllegalStateException("This order is no longer Submitted.")
   val tracked=(o.items).filter{it.productId!=null}
   val snaps=tracked.map{tx.get(db.collection("products").document(it.productId!!))}
   tracked.forEachIndexed{i,it->{val have=snaps[i].getDouble("stockOnHand")?:0.0;if(it.qty>have)throw IllegalStateException("Insufficient stock for ${it.desc}: need ${it.qty}, have $have")}}
   tx.update(orderRef,mapOf("status" to "Approved","stockApplied" to true,"approvedAt" to Timestamp.now(),"updatedAt" to Timestamp.now()))
   tracked.forEachIndexed{i,it->{val snap=snaps[i];if(!snap.exists())return@forEachIndexed;val ref=db.collection("products").document(it.productId!!);val old=snap.getDouble("stockOnHand")?:0.0;val next=old-it.qty;tx.update(ref,mapOf("stockOnHand" to next,"updatedAt" to Timestamp.now()));tx.set(db.collection("stockMovements").document(),mapOf("productId" to it.productId,"productName" to (snap.getString("productName")?:""),"packLabel" to (snap.getString("packLabel")?:""),"type" to "order-approved","delta" to -it.qty,"previousStock" to old,"newStock" to next,"reason" to "","orderId" to o.id,"orderNo" to o.orderNo,"createdBy" to uid,"createdByEmail" to email,"createdAt" to Timestamp.now()))}
  }.await()
 }
 suspend fun markOrderInvoiced(id:String,invoiceId:String,invoiceNo:String){db.runTransaction { tx -> val ref=db.collection("orders").document(id);val s=tx.get(ref);if(!s.exists()||s.getString("status")!="Approved")throw IllegalStateException("Order is no longer Approved.");tx.update(ref,mapOf("status" to "Invoiced","invoiceId" to invoiceId,"invoiceNo" to invoiceNo,"invoicedAt" to Timestamp.now(),"updatedAt" to Timestamp.now()))}.await()}
 suspend fun markDelivered(id:String,uid:String,email:String){db.runTransaction { tx -> val ref=db.collection("orders").document(id);val s=tx.get(ref);if(!s.exists()||s.getString("status")!="Invoiced")throw IllegalStateException("This order is no longer ready for delivery.");tx.update(ref,mapOf("status" to "Delivered","deliveredBy" to uid,"deliveredByEmail" to email,"deliveredAt" to Timestamp.now(),"updatedAt" to Timestamp.now())) }.await()}
 suspend fun addVisit(v:Visit,uid:String,email:String,customerId:String){db.collection("visits").add(mapOf("customerId" to customerId,"customerName" to v.customerName,"repId" to uid,"repEmail" to email,"date" to nowDate(),"outcome" to v.outcome,"reasonNoOrder" to v.reason.ifBlank{null},"reasonNotes" to v.notes,"orderId" to null,"orderNo" to null,"createdAt" to Timestamp.now())).await()}
}
